project:
  type: website
  output-dir: docs

website:
  title: "Science ouverte à l'UMI SOURCE"
  navbar:
    left:
      - href: index.qmd
        text: Introduction
      - href: data_info.qmd
        text: donnees_de_recherche
      - href: PGD.qmd
        text: PGD
      - href: repository.qmd
        text: entrepot
      - href: DP.qmd
        text: datapaper

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



