project:
  type: website
  output-dir: docs

website:
  title: "Science ouverte à l'UMI SOURCE"
  navbar:
    left:
      - href: index.qmd
        text: Introduction
      - href: data_info.qmd
        text: Éléments introductifs sur les données
      - href: PGD.qmd
        text: Élaborer un Plan de Gestion des Données (PGD)
      - href: repository.qmd
        text: Déposer ses données
      - href: DP.qmd
        text: Publier un data paper

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



